---
# role: samba_ad_objects
# file: tasks/main.yml

- name: SAMBA_AD_OBJECTS | Configure domain directory objects
  ansible.builtin.import_tasks: directory.yml
  module_defaults:
    group/jomrr.samba.all:
      server: "{{ samba_ad_objects_server }}"
      realm: "{{ samba_ad_objects_realm | upper }}"
      bind_username: Administrator
      bind_password: "{{ samba_ad_objects_admin_password }}"
